/**
 * AlarmDetail.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface AlarmDetail : UITableViewController <UITextFieldDelegate>

/**
 * IBOutlet songs
 */
@property (weak, nonatomic) IBOutlet UILabel *songs;

/**
 * IBOutlet switch
 */
@property (weak, nonatomic) IBOutlet UISwitch *switch;

/**
 * IBOutlet title
 */
@property (weak, nonatomic) IBOutlet UITextField *title;

@end
