/**
 * SendAlarmController.m
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

#import "SendAlarmController.h"

@interface SendAlarmController ()

@end
