/**
 * SendAlarmController.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface SendAlarmController : UIViewController <UIControl$OnValueChangedListener>

/**
 * IBOutlet alarmDetail
 */
@property (weak, nonatomic) IBOutlet UIView *alarmDetail;

/**
 * IBOutlet datePicker
 */
@property (weak, nonatomic) IBOutlet UIDatePicker *datePicker;

@end
