/**
 * SettingController.m
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

#import "SettingController.h"

@interface SeetingController ()

@end
