/**
 * SettingController.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface SeetingController : UIViewController <UIControl$OnValueChangedListener>

/**
 * IBOutlet tingTable
 */
@property (weak, nonatomic) IBOutlet SettingTableViewController *tingTable;

@end
