/**
 * SettingTableViewController.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface SettingTableViewController : UITableViewController <UITextFieldDelegate>

/**
 * IBOutlet lastwakeup
 */
@property (weak, nonatomic) IBOutlet UILabel *lastwakeup;

/**
 * IBOutlet nbping
 */
@property (weak, nonatomic) IBOutlet UILabel *nbping;

/**
 * IBOutlet nbwakeup
 */
@property (weak, nonatomic) IBOutlet UILabel *nbwakeup;

/**
 * IBOutlet partenaire
 */
@property (weak, nonatomic) IBOutlet UITextField *partenaire;

/**
 * IBOutlet turnoff
 */
@property (weak, nonatomic) IBOutlet UISwitch *turnoff;

@end
