/**
 * WakeUpLoveMainController.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface WakeUpLoveMainController : UIViewController <UITableViewDataSource>

/**
 * IBOutlet alarmTable
 */
@property (weak, nonatomic) IBOutlet UITableView *alarmTable;

/**
 * IBAction editMode
 * Selector: editMode
 */
-(IBAction) editMode;

/**
 * IBAction unwindToWakeUpLove
 * Selector: unwindToWakeUpLove:
 */
-(IBAction) unwindToWakeUpLove:(UIStoryboardSegue*) segue;

@end
