/**
 * WakeUpLoveMainController.m
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

#import "WakeUpLoveMainController.h"

@interface WakeUpLoveMainController ()

@end
