/**
 * FirstLaunchThreeController.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface FirstLaunchThreeController : UIViewController <UIControl$OnValueChangedListener,UITextFieldDelegate>

/**
 * IBOutlet datePicker
 */
@property (weak, nonatomic) IBOutlet UIDatePicker *datePicker;

/**
 * IBOutlet meetCity
 */
@property (weak, nonatomic) IBOutlet UITextField *meetCity;

@end
