/**
 * FirstLaunchOneController.m
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

#import "FirstLaunchOneController.h"

@interface FirstLaunchOneController ()

@end
