/**
 * FirstLaunchTwoController.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface FirstLaunchTwoController : UIViewController <UITextFieldDelegate>

/**
 * IBOutlet partenaireName
 */
@property (weak, nonatomic) IBOutlet UITextField *partenaireName;

/**
 * IBOutlet partenairePhone
 */
@property (weak, nonatomic) IBOutlet UITextField *partenairePhone;

@end
