/**
 * FirstLaunchOneController.h
 * 
 * This file has been auto-generated by
 * RoboVM's Interface Builder Integrator.
 * DO NOT MODIFY!
 */

@interface FirstLaunchOneController : UIViewController <UITextFieldDelegate>

/**
 * IBOutlet gender
 */
@property (weak, nonatomic) IBOutlet UISegmentedControl *gender;

/**
 * IBOutlet name
 */
@property (weak, nonatomic) IBOutlet UITextField *name;

@end
